import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="flex flex-col min-h-screen gap-6 px-6 py-6">
      <Head>
        <title>Next.js + Tailwind CSS Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <div className="flex flex-col items-start px-16 py-8 transition-all rounded-xl bg-neutral-50 drop-shadow-xl ">
          <h1 className="text-2xl font-bold">Spotify API</h1>
          <p className="py-1 text-base font-medium text-neutral-600">Starter pack</p>
        </div>
      </main>

    </div>
  )
}

export default Home
